# Generated by Django 5.2.8 on 2025-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('tool_schema', models.JSONField(blank=True, default=dict)),
                ('allowed_channels', models.JSONField(blank=True, default=list)),
                ('routing_rules', models.JSONField(blank=True, default=dict)),
                ('model_backend', models.CharField(default='vllm', max_length=32)),
                ('model_name', models.CharField(default='qwen2.5-14b-instruct', max_length=255)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=512)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'slug'], name='agents__tenant__688b9f_idx'), models.Index(fields=['tenant_id', 'is_active'], name='agents__tenant__c48664_idx')],
                'unique_together': {('tenant_id', 'slug')},
            },
        ),
    ]
