# Generated by Django 5.2.8 on 2025-11-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['routing_rules'], name='agents__routing_341b6f_idx'),
        ),
    ]
