# Generated by Django 5.2.8 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('faq', 'FAQ'), ('policy', 'Policy'), ('product', 'Product'), ('historical_conversation', 'Historical Conversation'), ('manual', 'Manual')], default='manual', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('storage_uri', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'source'], name='knowledge_a_tenant__62469b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMemorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('summary_type', models.CharField(choices=[('lifetime', 'Lifetime'), ('last_90_days', 'Last 90 Days'), ('last_case', 'Last Case')], default='lifetime', max_length=32)),
                ('content', models.TextField()),
                ('structured_metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_summaries', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'summary_type'], name='knowledge_a_custome_ac5486_idx')],
                'unique_together': {('tenant_id', 'customer', 'summary_type')},
            },
        ),
    ]
