# Generated by Django 5.2.8 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('fb_messenger', 'Facebook Messenger'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('web', 'Web')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='agents.agentprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('fb_messenger', 'Facebook Messenger'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('web', 'Web')], default='whatsapp', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='conversations.conversation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('structured_event', 'Structured Event')], default='text', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('llm_metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant_id', 'channel', 'status'], name='conversatio_tenant__6636d6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', 'status'], name='conversatio_custome_1640d0_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['tenant_id', 'scheduled_for'], name='conversatio_tenant__6ecff5_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['customer', 'status'], name='conversatio_custome_ca4060_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_a1ac08_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant_id', 'message_type'], name='conversatio_tenant__08ccc2_idx'),
        ),
    ]
