# Generated by Django 5.2.8 on 2025-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_message_id'], name='conversatio_externa_819b28_idx'),
        ),
    ]
