# Generated by Django 5.2.8 on 2025-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=128)),
                ('actor', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'event_type'], name='analytics_a_tenant__53653d_idx'), models.Index(fields=['created_at'], name='analytics_a_created_08c04f_idx')],
            },
        ),
    ]
