# Generated by Django 5.2.8 on 2025-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(blank=True, max_length=64)),
                ('agent_id', models.IntegerField(blank=True, null=True)),
                ('resolution_rate', models.FloatField(default=0.0)),
                ('deflection_rate', models.FloatField(default=0.0)),
                ('aht_seconds', models.FloatField(default=0.0)),
                ('tool_call_counts', models.JSONField(blank=True, default=dict)),
                ('payment_conversion_rate', models.FloatField(default=0.0)),
                ('model_backend', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('avg_llm_latency_ms', models.FloatField(default=0.0)),
                ('total_conversations', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='analytics_a_date_9c5243_idx'), models.Index(fields=['channel'], name='analytics_a_channel_337ef7_idx'), models.Index(fields=['agent_id'], name='analytics_a_agent_i_ea77bc_idx')],
                'unique_together': {('tenant_id', 'date', 'channel', 'agent_id')},
            },
        ),
    ]
