# Generated by Django 5.2.8 on 2025-11-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_event_t_f90eaa_idx',
            old_name='analytics__event_ty_4a8260_idx',
        ),
        migrations.AddField(
            model_name='dailykpi',
            name='tool_success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailykpi',
            name='total_tool_calls',
            field=models.IntegerField(default=0),
        ),
    ]
