# Generated by Django 5.2.8 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('fb_messenger', 'Facebook Messenger'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('web', 'Web')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'channel', 'external_id'], name='customers_a_tenant__d4aef7_idx')],
                'unique_together': {('tenant_id', 'channel', 'external_id')},
            },
        ),
    ]
