# Generated by Django 5.2.8 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMInferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('model_backend', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='agents.agentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'model_backend'], name='llm_llm_tenant__e7c69c_idx'), models.Index(fields=['agent', 'created_at'], name='llm_llm_agent_i_938bda_idx')],
            },
        ),
    ]
