# Generated by Django 5.2.8 on 2025-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('fb_messenger', 'Facebook Messenger'), ('shopify', 'Shopify'), ('magento', 'Magento'), ('web', 'Web')], max_length=32)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'channel', 'external_event_id'], name='channels_ap_tenant__3c3b11_idx'), models.Index(fields=['processed'], name='channels_ap_process_276845_idx')],
            },
        ),
    ]
