# Generated by Django 5.2.8 on 2025-11-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhookevent',
            unique_together={('tenant_id', 'channel', 'external_event_id')},
        ),
    ]
